### ISSUE TITLE
Add Global Scoreboard

### ISSUE THREAD

**Issue by jsolly** [jsolly/GeoAsteroids#161]
## Context 
Users should be able to see the global top 10 scores when the game ends

## Current Behavior/Workaround
Only showing current user's top score via local storage

## Things to consider
Store in a flat file or database?
Any issues with concurrency if using a flat file?
Will need to provide a way to add three-letter username to associate with score
Will need placeholders for the top 10 scores to start

**Comment by jsolly** [comment]
@shawnamays do you have any suggestions for what should go in the scoreboard or other enhancements related to it?

**Comment by jsolly** [comment]
Implementation finished
- Using a MongoDB database for the high scores
- Serverless functions for GET/POST to api/highscores
- The name for each highscore is a three letter capitalized name
- The database only maintains the top 10 scores

**Comment by shawnamays** [comment]
Hey John!

Not sure how this email bypassed me but I’m really excited to see the new
features! I’ll check it out tonight after I get off work!
